# Generated by Django 4.2.7 on 2024-01-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('armor_class', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('hit_dice', models.CharField(max_length=255)),
                ('speed', models.JSONField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('skills', models.JSONField()),
                ('damage_vulnerabilities', models.CharField(blank=True, default='none', max_length=255)),
                ('damage_resistances', models.CharField(max_length=255)),
                ('damage_immunities', models.CharField(max_length=255)),
                ('condition_immunities', models.CharField(max_length=255)),
                ('challenge_rating', models.CharField(max_length=10)),
                ('actions', models.JSONField()),
                ('special_abilities', models.JSONField()),
                ('spell_list', models.JSONField()),
                ('page_no', models.IntegerField()),
                ('environments', models.JSONField()),
                ('img_main', models.URLField()),
            ],
        ),
    ]
